---
- hosts: cves.wiseeyesent.com
  vars:
    - playbook: "cvesearch.test_env"
    - home: "{{ ansible_env.HOME }}"
    - bindir: "{{ home }}/.ansible/bin"
    - scripts:
      - cve-save.py
      - cve-check.py
  tasks:
  - name: Add MySQL Test User
    mysql_user:
      name: testusr
      host: localhost
      priv: cves_dev.*:ALL
      password: '!!!MySQLT3stUs3r!!!'
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Prep script destination dir
    file:
      path: "{{ bindir }}"
      state: directory
  - name: Add .ansible/bin to $PATH
    lineinfile:
      path: "{{ home }}/.bashrc"
      regexp: '^PATH=(.*)'
      line: 'PATH=\1:{{ bindir }}'
      backrefs: yes
      backup: yes
  - name: Upload cvesearch Python Scripts
    copy:
      src: "../resources/{{ item }}"
      dest: "{{ bindir }}/{{ item }}"
      mode: 0700
    with_items: "{{ scripts }}"
  - name: Prep User bin Dir
    file:
      path: "{{ home }}/bin"
      state: directory
  - name: Symlink cvesearch Python Scripts
    file:
      state: link
      dest: "{{ home }}/bin/{{ item }}"
      src: "{{ bindir }}/{{ item }}"
    with_items: "{{ scripts }}"
  - name: Upload config.ini
    template:
      src: "../templates/config.ini.j2"
      dest: "{{ home }}/config.ini"
  - name: Execute cve-save.py test script
    shell: "{{ bindir }}/cve-save.py"
